### ISSUE TITLE
USER STORY: As a "super user" I can update FAQ section on home page so that my potential customers have better information before sign up.

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#1]
EPIC: Super User Functionalities

As a **superuser** I can **update FAQ section on my home page** so that **my potential customers have better info before signing up**.

**Acceptance Criteria**

- [ ] The user can update or delete an existing FAQ.
- [ ] The user can add as many FAQs as needed.
- [ ] After updation the user is redirected to the home page to confirm that changes are reflected
- [ ] If the user tries to post a question while leaving an answer field empty, a prompt appears to correct him.

**Tasks**
