### ISSUE TITLE
USER STORY : As a user I can log my transactions along with categories and date so that I can keep an eye on it

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#10]
EPIC: User Engagement

As a **user** I can **log my transactions along with categories and date** so that **I can keep an eye on it**

**Acceptance Criteria**

- [x] The user can locate "add" button quickly and easily
- [x] The user can distinguish between income and expense
- [x] The user can log expenses with the default date selected "today", but with the ability to back date

**Tasks**

- [x] Create UI for add button
- [x] Create UI for adding income along with date and categories
- [x] Create UI to distinguish between income and exepnse
- [x] Connect to database and test connection

**Comment by ysgurjar** [comment]
All acceptance criteria met and tasks completed. The functionality has been maually tested on deployed database.

An _is_income field is added, Which opens up possibilty of creating income as well for provided categories. This feature is important as sometimes you get cashback , tax refund etc (positive cashflow)
