### ISSUE TITLE
USER STORY : As a user I can update my expenses so that I can correct my mistakes

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#11]
EPIC: User Engagement

As a **user** I can **update my expenses** so that **I can correct my mistakes**.

**Acceptance Criteria**

- [x] User can update expense category and date and amount
- [x] User cannot update expense to future date
- [x] User can delete expense

**Tasks**

- [x] Create a UI where the user can see a list of expenses
- [x] Upon clicking expense, the user can edit an expense
- [x] User can delete expense after confirmation

**Comment by ysgurjar** [comment]
All tasks and acceptance criteria has been fullfilled and tested.
