### ISSUE TITLE
USER STORY : As a user I can delete my account so that I can delete my identity and data from the platform

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#12]
EPIC: User Engagement

As a **user** I can **delete my account** so that **I can delete my identity and data from the platform**.

**Acceptance Criteria**

- [ ] User must request an access right to delete an account
- [ ] The account deletion is possible only after the site owner grants admin rights

**Tasks**

- [ ] Create a UI in settings menu to ask for admin rights to delete account
- [ ] In the meantime the the access is granted, the "status" must show pending approval
- [ ] After the admin rights are granted, the user can delete the account
- [ ] After account deletion, the user is redirected to home page

**Comment by ysgurjar** [comment]
The ability to delete the account has been restricted to "superuser" from django admin panel.
