### ISSUE TITLE
USER STORY : As a user, I can anylse my expenses for given period of time for each category so that I can manage my future spending

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#15]
EPIC: User Engagement

As a **user** I can **I can anylse my expenses for a given period of time for each category** so that **I can manage my future spending**

**Acceptance Criteria**

- [ ] User can select a custom date range
- [ ] User can select a wallet to include or exclude

**Tasks**

- [ ] Create a UI for presenting expenses 
- [ ] The visible expenses can further be customised by date and wallet filter
- [ ] Crosscheck the database result from query

**Comment by ysgurjar** [comment]
The reason for changin this to "could have" is because the feature is not neccessary for MVP. 

What is important for MVP is to have some visulisation where user can see spending and income. This is covered by another user story and github issue.
