### ISSUE TITLE
USER STORY : As a user I can visualise my expense in pie chart and bar chart so that I can have see my spending habits and distributions

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#16]
EPIC: User Engagement

As a **user** I can **visualise my expense in pie chart and bar chart** so that **have see my spending habits and distributions**

**Acceptance Criteria**

- [ ] The user can select custom date for visualisation
- [ ] The user can include or exclude a given wallet or set of wallets from visualisation

**Tasks**

**Comment by ysgurjar** [comment]
Including customer filters where user can select wallet and date will be left to next release.

However, it is still important to include "some visulisation" as a part of MVP

So, a new task and acceptance criteria will be

**Modified Acceptance Criteria**

- [ ] Include some visulisation where user can have some overview of their expense

**Comment by ysgurjar** [comment]
A simple bar chart is implemented which shows total expenses incurred and income received across all the wallet (summing up related transactions for all wallets)
