### ISSUE TITLE
USER STORY : As a user when I encounter something unexpected I want to know why that happened with an optional navigation

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#17]
EPIC: User Engagement

As a **user** I can **I want to know why that happened ** with an optional navigation

**Acceptance Criteria**

- [ ] User can see the message that something unexpected happened and possible reason
- [ ] Post error, user can navigate to home page or any other location from the same page without confusion

**Tasks**

- [ ] Create 404 page
- [ ] Create 500 page
- [ ] Provide an option to contact site owner 
- [ ] Provide an option to navigate back to home screen or previous menu

**Comment by ysgurjar** [comment]
Apart from 500 page, all other pages are implemented.

500 page is low in priority, so it is not necessary given the time constraint
