### ISSUE TITLE
USER STORY : As a superuser, I can give admin rights to app users so that they can delete their own account

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#2]
EPIC: Super User Functionality

As a **superuser** I can **give admin rights to app users** so that **they can delete their account**.

**Acceptance Criteria**

- [ ] A user can request admin rights to delete an account
- [ ] Super users can approve or withdraw admin rights for a given account.
- [ ] Once the user deletes the account, the account should not appear again

**Tasks**

- [ ] Create a front-end for the superuser when he can see the list of accounts.
- [ ] Create a front end for superusers from where admin rights are given or withdrawn.
- [ ] Notify the admin when a user deletes the account.

**Comment by ysgurjar** [comment]
Notes after discussion:

It is important to have user freedom to delete their own account. However, it will be nice to implement this functionality after two-factor authentication is implemented. WIthout that, the site is bit more vulnerable and unforeseen attacks can lead to loosing customer data.

Hence it is not implemented just yet.

The customer can contact via "contact us" form if he wants the account deleted. The account deletion is possible by administration from django admin panel.

Sice it is moved to next release, it has been changed from "must have" to "should have".
