### ISSUE TITLE
USER STORY : As a super user I can see the messages sent to me via Contact Us form, so that I can address it for better customer engagement.

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#3]
EPIC: Super User Functionality

As a **superuser** I can **see the messages sent to me via Contact Us form** so that **I can address it for better customer engagement.**

**Acceptance Criteria**

- [ ] The superuser would like to receive an email notification.

**Tasks**

- [ ] The query to superuser cannot be submitted without a valid email address, an empty text field, 
- [ ] Link an email service to FAQ form
- [ ] Test the email service

**Comment by ysgurjar** [comment]
This is related to [another user story](https://github.com/ysgurjar/pp4_expense_tracker/issues/5), which covers as to why we moved away from form and instead went with email service.

So, at the moment if user can send email to admin via contact us email id.

The issue is closed as it is related and already covered.
