### ISSUE TITLE
USER STORY : As a first-time user I can read what the website is about so that I can decide whether to sign up.

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#4]
EPIC: User Engagement

As a **first-time user** I can **read what the website is about** so that **I can decide whether to sign up**.

**Acceptance Criteria**

- [x] The user should be able to read the description of the app including features
- [x] The user should be able to locate the button to sign up.

**Tasks**

- [x] Create a home page with hero and features section
- [x] The home page should have clear sign up button

**Comment by ysgurjar** [comment]
All the tasks are completed and tested to verify acceptance criteria are met.
