### ISSUE TITLE
USER STORY : As a first time user I can contact site owner if I have any questions so that I can decide whether to sign up

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#5]
EPIC: User Engagement

As a **first time user** I can **contact the site owner if I have any questions** so that **I can decide whether to sign up**.

**Acceptance Criteria**

- [ ] The user should have a sufficient text field to write a query to the site owner
- [ ] The user should be able to provide his email for the site owner to reply

**Tasks**

- [ ] Create a form on a home page with validation
- [ ] Link an email service to form
- [ ] Once submitted, the user should receive a feedback prompt

**Comment by ysgurjar** [comment]
Notes following discussion:
It is important to have to contact us functionality, however, it is not important to have it accessible only through form. The better idea is to have the client use their email service where they are not limited by text fields and are able to upload screenshots, video recordings etc.

Hence, the new acceptance criteria and tasks are :
 
**Acceptance Criteria**

- [x]  The user should be able to find contact us section
- [x]  The user should be able to find email id

**Tasks**

- [x] Create a contact us section on home page with email address to site owner.

**Comment by ysgurjar** [comment]
The task is completed and tested to verify acceptance criteria are met.
