### ISSUE TITLE
USER STORY : As a first time user I can create an account so that I can start using the app

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#6]
EPIC: User Authentication and Authorisation

As a **first time user** I can **create an account** so that **I can start using the app**

**Acceptance Criteria**

- [ ] The user can create an account with a username, email address and password
- [ ] The user should receive the account creation confirmation
- [ ] Only one email ID can be associated with one user name

**Tasks**

- [ ] Create a sign in page
- [ ] Test sign in page form for duplicate email ID, password requirement match
- [ ] Link an email service
- [ ] Test an email service
- [ ] Feedback user for any discrepancy on sign in  form validation

**Comment by ysgurjar** [comment]
MVP now includes using a username and password. Not the usermail ID. 

So, the new Acceptance criteria are as follows:

**Acceptance Criteria**

- [x]  The user can create an account with a username and  password
- [x]  The user should receive the account creation confirmation - this will only be a pop up notification immediately after successful account creation.
- [x]  Only one username can be associated with one user name

**Tasks**

- [x]  Create a sign in page
- [x]  Test sign in page form for duplicate user ID, password requirement match
- [x]  Feedback user for any discrepancy on sign in form validation

**Comment by ysgurjar** [comment]
All the tasks have been completed and tested to verify that acceptance criteria are met.
