### ISSUE TITLE
USER STORY : As a recurring user I can log in and log out so that I can update my expenses

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#7]
EPIC: User Authentication and Authorisation

As a **recurring user** I can **log in and log out** so that **I can update my expenses**.

**Acceptance Criteria**

- [ ] The user can log in using email ID and password
- [ ] The user can log out with just a click of a button, after confirmation
- [ ] Post failed attempt, the user should know what is preventing the login

**Tasks**

- [ ] Create a login page with a user ID and password
- [ ] Link and test authentication and authorisation
- [ ] The user should receive feedback on failed login attempt , why it failed
- [ ] I can clearly see my log in or log out "state"

**Comment by ysgurjar** [comment]
Notes following discussion:

Log-in and logout functionalities are must-have features. However, it is not important to have an email ID as MVP.

Additionally, an observation was made that almost all the websites do not ask for confirmation, on clicking the logout button. So, best to implement similar behaviour.

Hence new acceptance criteria and tasks are slightly different than what was originally planned. They are mentioned below.

Acceptance Criteria

- [ ]  The user can log in using email ID and password
- [ ]  The user can log out with just a click of a button, after confirmation
- [ ]  Post failed attempt, the user should know what is preventing the login

Tasks

 

- [ ] Create a login page with a user ID and password
- [ ]  Link and test authentication and authorisation
- [ ]  The user should receive feedback on failed login attempt , why it failed
- [ ]  I can clearly see my log in or log out "state"

**Comment by ysgurjar** [comment]
All the tasks are completed and tested to confirm acceptance criteria.
