### ISSUE TITLE
USER STORY :  As a recurring user I can recover my account in case I forgot my password so that my data is not lost

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#8]
EPIC: User Authentication and Authorisation

As a **recurring user** I can **recover my account in case I forgot my password** so that **my data is not lost**.

**Acceptance Criteria**

- [ ] The user can access forgot password functionality
- [ ] Using forgot password, the user will receive a link to reset the account
- [ ] Using the reset link he can provide a new password
- [ ] After the new password is provided, the user can log in using the new password.

**Tasks**

- [ ] Provide forgot password functionality along with the login page
- [ ] The user will be given a password reset link on the provided email ID
- [ ] The link will redirect to a password reset page
- [ ] The new password cannot be the same as the old password
- [ ] The new password must match the original password criteria
- [ ] Following password reset the user is redirected to the home page

**Comment by ysgurjar** [comment]
This relates to a user story where user logs in with user email ID and password.
However, it has been agreed that user will be using username and password instead for MVP.
So, it has been moved from "must have" to "could have"
