### ISSUE TITLE
USER STORY : As a user I can add more than wallets so that I can maintain seperate expense record for different bank accounts/cards.

### ISSUE THREAD

**Issue by ysgurjar** [ysgurjar/pp4_expense_tracker#9]
EPIC: User Engagement

As a **user** I can **add more than wallets** so that **rI can maintain seperate expense record for different bank accounts/cards**

**Acceptance Criteria**

- [ ] User can add as many wallets as needed
- [ ] User can rename wallet as many times as needed
- [ ] User can delete the wallet, but all the related transactions will be lost
- [ ] User cannot create another wallet with similar name

**Tasks**

- [ ] Add wallet CRUD functionality accessible from user settings
- [ ] Test wallet CRUD functionality
- [ ] Upon deletion of the wallet, the user should be redirected to wallets overview page
